name: refapp
services:
  refapp-db:
    image: hub.csaude.org.mz/sesp/mysql:8.4.2
    container_name: refapp-db
    stop_grace_period: 2h
    restart: unless-stopped
    ports:
      - "3320:3306"
    networks:
      - network
    environment:
    # -- BOF REMOVE AFTER DATABASE CREATION
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=openmrs_prod
      - MYSQL_USER=sesp
      - MYSQL_PASSWORD=sesp
    # -- EOF REMOVE AFTER DATABASE CREATION
      - MYSQL_DATA_DIRECTORY=/var/lib/mysql
    volumes:
      - /etc/localtime:/etc/localtime
      - ./database/conf:/etc/mysql
      - ./database/scripts:/scripts
      - /var/log/sesp/mysql:/var/log/mysql
      - /var/lib/sesp/mysql:/var/lib/mysql
  refapp-tomcat:
    image: hub.csaude.org.mz/sesp/tomcat:9.0.97
    container_name: refapp-tomcat
    stop_grace_period: 30m 
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - network
    depends_on:
      - "refapp-db"
    environment:
      DISA_ENVIRONMENT:
      DISA_API_USERNAME:
      DISA_API_PASSWORD:
    volumes:
      - /etc/localtime:/etc/localtime
      - ./tomcat/conf/openmrs-runtime.properties:/usr/local/tomcat/openmrs-runtime.properties
      - ./tomcat/conf/setenv.sh:/usr/local/tomcat/bin/setenv.sh
      - ./tomcat/logs:/usr/local/tomcat/logs
      - ./tomcat/data/webapps:/usr/local/tomcat/webapps
      - ./tomcat/data/OpenMRS:/usr/local/tomcat/.OpenMRS
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 30s 
      retries: 15

networks:
  network:
    driver: bridge
